### ISSUE TITLE
Reduce duplicate code

### ISSUE THREAD

**Issue by lmoesle** [Miragon/miranum-ide#145]
- [x] Description created
- [x] Reviewed by peer: @peterhnm 
- [ ] Prioritised

We have a lot of duplicate code in the miranum-ide. Especially in the miranum-console and miranum-cli.
We should try to migrate duplicates in these 2 apps to libraries.

```[tasklist]
- [ ] Check if we could use the nodejs fs lib in vscode extensions
- [ ] Move filesystem operations into a fs lib that may be used by console and cli app
- [ ] Move handling miranum.json into a lib
- [x] Create a miranum-vscode lib for reusable components (e.g FileSystemReader, Preview, TextEditor)
```

**Comment by peterhnm** [comment]
@lmoesle not really.
