### ISSUE TITLE
[Bug] - Resizing the pool causes buggy editor

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/miranum-ide#385]
**Describe the bug**
When I open a BPMN model in the VS Code Modeler and I want to resize the pool, the behaviour shown in the video occurs. 
It can be forced by expanding the pool to the top. Sometimes though, it happens in any given direction. 
It was a bit unfortunate to experience this behaviour during a live demo of our VS Code Modeler. 😢 

**To Reproduce**
1. Open a BPMN file in the VS-Code Modeler
2. Resize the pool in any given direction
3. If it does not show the behaviour shown in the video redo step 2
4. See behaviour which is shown in the video

**Expected behaviour**
Resizing of a pool does not cause the Modeler to reset view point to a white canvas. Editing the size of the pool should be always possible 

**Screenshots**
Video: 
![video of the bug](https://github.com/Miragon/miranum-ide/assets/30292227/934f5695-0006-4290-8c36-bbb54e16a379)

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2 (22G91)
 - VS Code Version: 1.82.1
 - Miranum Modeler: v0.5.3

**Comment by peterhnm** [comment]
The bug occurs because of this [module](https://github.com/bpmn-io/align-to-origin).
It is described [here](https://github.com/bpmn-io/align-to-origin/issues/2)

**Comment by Hafflgav** [comment]
Hey @peterhnm 👋 
Thanks for the very fast fix of the problem 🚀  
It doesn't crash anymore 👍 

But besides, I have found another behaviour related to the viewport, which was a bit unexpected to me: 

![Miranum IDE Behaviour](https://github.com/Miragon/miranum-ide/assets/30292227/ceccd357-d4ac-4ca5-b50d-abb25c569ced)

My expectation would be that the viewport does not change when placing a BPMN-Element on the modelling canvas. 
This behaviour can especially be seen when moving only start event on the canvas. 

Let me know what you think about this!

**Comment by peterhnm** [comment]
I like this behavior because it means less scrolling for me, for example after a resize of a pool.

What do you think about configuring it so that the user can turn this behavior on and off?

[Vs Code Setting](https://github.com/Miragon/miranum-ide/assets/100686712/80c44d2a-dd79-4926-8f8d-e00039d45e20)
