### ISSUE TITLE
Forms and Element Templates should be selectable in the editor, even if they are in subfolders

### ISSUE THREAD

**Issue by xdoo** [Miragon/miranum-ide#451]
**Is your feature request related to a problem? Please describe.**
I use one project for several processes. I have several forms in each process. This results in a large number of forms in the forms folder.

**Describe the solution you'd like**
It would be nice if I had the option of organizing the forms in subfolders. Of course, this is possible in principle. However, I cannot select a form in the Process Editor within a Human Task that is located in a subfolder under "forms". It would be nice if that were possible.

**Describe alternatives you've considered**
Forms should be selectable, no matter how deep they are in a structure in the "forms" folder. You can also limit this to one or two levels, but having everything in the top level folder is not practical for many forms.

**Comment by lmoesle** [comment]
@xdoo Thanks for your feature request. So far we didn't consider supporting monorepos for process development.

Therefore, the described behaviour should work for all types of artifacts (forms, configs, ...). This feature will affect the deployment and project generation domain and the bpmn-modeller. I will add todos to the tasklist.

A quick workaround that comes to my mind could be to create for each process a subdirectory with it's own `miranum.json`. That should be possible at the moment and help you to better organize your processes.

**Comment by xdoo** [comment]
Hi @lmoesle. 

thanks for your reply.

From my point of view, this has nothing to do with monorepo or not - but maybe I misunderstand the naming at this point. I create a project and can also create n process definitions in this project. I understood this construct as a storage location for all my processes in the project ;) 

The deployment also works if the files are in subfolders (maybe you should check this again explicitly, but I'm pretty sure it worked for me with the CLI).

I don't know if the creation of the files belongs here. When I create a new file via the IDE (I know, it's not the CLI) - for example a form, it doesn't even end up in the "forms" folder, even though it's specified in the config. That's not a problem - I just move it to where I need it.

**Comment by lmoesle** [comment]
I created an example project to replicate you described behaviour (https://github.com/Miragon/miranum-ide/tree/feature/monorepo-modelling-support/resources/monorepo-example). The bpmn modeller does not detect files in subfolders and therefore does not show any suggestions.
This behaviour occurs for forms and element-templates. For the other artifact types suggestions are not supported.

**Expected behaviour**

- Suggestions for forms from subdirectories (e.g. `forms/foo`) are shown in the modeller
- Suggestions for element-templates from subdirectories (e.g. `element-templates/mail`) are shown in the modeller

**Comment by peterhnm** [comment]
Hi @xdoo with the newest release 0.5.7 this issue should be resolved.

**Comment by xdoo** [comment]
@peterhnm @lmoesle Great - Thank you 😃
